# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9ca9f78ec7c821bfa3acdf8e7eb4d520017f3b0c8921018e0969f25c15641ec66713426e17379b2fb60a3469e66adf318e82ef80d0abf6e7528b7295581cf63

test:
  secret_key_base: d9cc32f8b1e0fc492872cfa0f695c3541f396472cbea62f34f3f6f3887e92786346cb78aa46648b34d4f51b1e0682811a8eb13eb65c78ce4b5565fff343c72e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
